/*
 * WidgetClone.java
 *
 * Created on November 3, 2006, 2:03 AM
 */

package org.jdesktop.swingx.painter.demo;

import java.awt.Color;
import org.jdesktop.swingx.JXLabel;
import org.jdesktop.swingx.JXPanel;
import org.jdesktop.swingx.painter.CompoundPainter;
import org.jdesktop.swingx.painter.GlossPainter;
import org.jdesktop.swingx.painter.MattePainter;
import org.jdesktop.swingx.painter.RectanglePainter;

/**
 *
 * @author  joshy
 */
public class WidgetClone extends javax.swing.JFrame {
    
    /** Creates new form WidgetClone */
    public WidgetClone() {
        initComponents();
        RectanglePainter mainRect = new RectanglePainter(0,0,0,0,
                10,10,true,Color.BLACK,0,Color.BLACK);
        mainRect.setStyle(RectanglePainter.Style.FILLED);
        mainRect.setAntialiasing(true);//RectanglePainter.Antialiasing.On);
        GlossPainter gloss = new GlossPainter();
        gloss.setPosition(GlossPainter.GlossPosition.TOP);
        mainPanel.setBackgroundPainter(
                new CompoundPainter(mainRect,gloss));
        
        RectanglePainter greyBorder = new RectanglePainter(0,0,1,1,5,5);
        greyBorder.setBorderPaint(Color.DARK_GRAY);
        greyBorder.setBorderWidth(1.5f);
        greyBorder.setAntialiasing(true);//RectanglePainter.Antialiasing.On);
        greyBorder.setStyle(RectanglePainter.Style.OUTLINE);
        ((JXPanel)panel19).setBackgroundPainter(greyBorder);
        
        ((JXLabel)hours).setForegroundPainter(greyBorder);
        ((JXLabel)minutes).setForegroundPainter(greyBorder);
        ((JXLabel)seconds).setForegroundPainter(greyBorder);
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        mainPanel = new org.jdesktop.swingx.JXPanel();
        jPanel2 = new javax.swing.JPanel();
        wii = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panel19 = new JXPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        seconds = new JXLabel();
        minutes = new JXLabel();
        hours = new JXLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setOpaque(false);
        wii.setFont(new java.awt.Font("Lucida Grande", 0, 24));
        wii.setForeground(new java.awt.Color(102, 102, 102));
        wii.setText("Wii");
        wii.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 8));
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("CLOCK");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 8));
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("COUNTDOWN");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(wii)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel2)
                    .add(jLabel3))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(wii)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(10, 10, 10)
                        .add(jLabel3))
                    .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
        );

        panel19.setOpaque(false);
        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 48));
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("19");
        jLabel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 8));

        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("DAYS");
        jLabel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 8));

        org.jdesktop.layout.GroupLayout panel19Layout = new org.jdesktop.layout.GroupLayout(panel19);
        panel19.setLayout(panel19Layout);
        panel19Layout.setHorizontalGroup(
            panel19Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panel19Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .add(panel19Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel4)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel5)))
        );
        panel19Layout.setVerticalGroup(
            panel19Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panel19Layout.createSequentialGroup()
                .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        seconds.setFont(new java.awt.Font("Lucida Grande", 0, 10));
        seconds.setForeground(new java.awt.Color(102, 102, 102));
        seconds.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        seconds.setText("14 SECONDS");
        seconds.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 8));

        minutes.setFont(new java.awt.Font("Lucida Grande", 0, 10));
        minutes.setForeground(new java.awt.Color(102, 102, 102));
        minutes.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        minutes.setText("10 MINUTES");
        minutes.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 8));

        hours.setFont(new java.awt.Font("Lucida Grande", 0, 10));
        hours.setForeground(new java.awt.Color(102, 102, 102));
        hours.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        hours.setText("6 HOURS");
        hours.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 8));

        org.jdesktop.layout.GroupLayout mainPanelLayout = new org.jdesktop.layout.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, panel19, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, seconds, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, hours, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, minutes, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(panel19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(hours)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(minutes)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(seconds)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(mainPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .add(mainPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WidgetClone().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hours;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private org.jdesktop.swingx.JXPanel mainPanel;
    private javax.swing.JLabel minutes;
    private javax.swing.JPanel panel19;
    private javax.swing.JLabel seconds;
    private javax.swing.JLabel wii;
    // End of variables declaration//GEN-END:variables
    
}
